# Generated by Django 4.1 on 2022-09-01 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("u", "User"), ("b", "Buisness Owner")], max_length=1
                    ),
                ),
            ],
            options={"db_table": "role",},
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(default="", max_length=254, unique=True)),
                ("password", models.CharField(default="", max_length=10)),
                ("fullname", models.CharField(default="", max_length=30)),
                ("contact_info", models.CharField(blank=True, max_length=10)),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="d2dapp.role"
                    ),
                ),
            ],
            options={"db_table": "profile",},
        ),
    ]
