# Generated by Django 4.1 on 2022-09-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("d2dapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role", name="role", field=models.CharField(max_length=20),
        ),
    ]
