# Generated by Django 4.1 on 2022-09-01 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("d2dapp", "0002_alter_role_role"),
    ]

    operations = [
        migrations.RenameModel(old_name="Role", new_name="UserRole",),
    ]
