# Generated by Django 4.1 on 2022-09-01 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("d2dapp", "0003_rename_role_userrole"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="role", new_name="UserRole",
        ),
    ]
