# Generated by Django 4.1 on 2022-09-01 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("d2dapp", "0005_rename_contact_info_profile_contact_info_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="Contact_info", new_name="contact_info",
        ),
        migrations.RenameField(
            model_name="profile", old_name="Email", new_name="email",
        ),
        migrations.RenameField(
            model_name="profile", old_name="Fullname", new_name="fullname",
        ),
        migrations.RenameField(
            model_name="profile", old_name="Location", new_name="location",
        ),
        migrations.RenameField(
            model_name="profile", old_name="Password", new_name="password",
        ),
        migrations.RenameField(
            model_name="userrole", old_name="Role", new_name="role",
        ),
    ]
