# Generated by Django 4.1 on 2022-09-13 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("d2dapp", "0011_product"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="profile",),
    ]
