# Generated by Django 4.1 on 2022-09-13 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("d2dapp", "0012_remove_product_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sub_Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(default="", max_length=20)),
                ("product_price", models.IntegerField()),
                ("description", models.TextField(blank=True, max_length=100)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="d2dapp.product"
                    ),
                ),
            ],
        ),
    ]
