# Generated by Django 4.1 on 2022-09-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("d2dapp", "0013_sub_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="sub_products",
            name="product_image",
            field=models.ImageField(default="default.png", upload_to="product_images/"),
        ),
        migrations.AlterField(
            model_name="sub_products",
            name="description",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="sub_products",
            name="product_name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
