# Generated by Django 4.1 on 2022-09-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("d2dapp", "0014_sub_products_product_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sub_products",
            name="product_owner",
            field=models.CharField(default="", max_length=20),
        ),
    ]
