# Generated by Django 4.1 on 2022-09-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("d2dapp", "0015_sub_products_product_owner"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="categories",),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="product",
            name="product_image",
            field=models.ImageField(default="default.png", upload_to="product_images/"),
        ),
        migrations.AddField(
            model_name="product",
            name="product_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="product_owner",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="product",
            name="product_price",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(name="Sub_Products",),
    ]
