# Generated by Django 4.1 on 2022-09-15 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("d2dapp", "0016_remove_product_categories_product_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="d2dapp.profile"
            ),
        ),
    ]
