# Generated by Django 4.1 on 2022-09-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("d2dapp", "0017_alter_product_product_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="product_owner", new_name="Profile",
        ),
    ]
