# Generated by Django 4.1 on 2022-09-15 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("d2dapp", "0018_rename_product_owner_product_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="Profile", new_name="profile",
        ),
    ]
