# Generated by Django 4.1 on 2022-09-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("d2dapp", "0020_rename_profile_product_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.FileField(default="default.png", upload_to="product_images/"),
        ),
    ]
